#!/usr/bin/python3


import sys
import time


def factorize(num):
    ''' this for Takes a number as input.
    Args:
        num: for input integer.
        Return: A tuple of two factors if the number is not a prime.
                None if the number is prime.
    '''
    for i in range(2, int(num**0.5)+1):
        if num % i == 0:
            return (i, num//i)
    return None


if __name__ == "__main__":


    ''' this for Reads the input file.
    '''
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit()


    input_file = sys.argv[1]


    try:
        with open(input_file, 'r') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print("File not found")
        exit()


    start_time = time.time()


    '''this loop for  in  over  line ,
        and calls factorize on each number.
        If factorize returns a tuple of factors,
        it factorization in the desired forma
    '''
    for line in lines:
        num = int(line.strip())
        factors = factorize(num)
        if factors:
            print(f"{num}={factors[0]}*{factors[1]}")


        ''' this for  If elapsed time exceeds 5 seconds,
            the program exits with an error message.
        '''
        if time.time() - start_time > 5:
            print("Time limit exceeded")
            exit()
